name: 'Live Preview'
description: 'A github action for live preview docker applications.'

branding:
  icon: 'activity'
  color: 'green'

inputs:
  protocol:
    description: 'The protocol to forward traffic to'
    default: http
  port:
    description: 'The port to forward traffic to'
    required: true
  ngrok_authtoken:
    description: 'Ngrok authorization token'
    required: true
outputs:
  url:
    description: 'Live preview URL.'

runs:
  using: "composite"
  steps:
    - run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      shell: bash
    - run: unzip -qq ngrok-stable-linux-amd64.zip
      shell: bash
    - run: ./ngrok authtoken ${{ inputs.ngrok_authtoken }}
      shell: bash
    - run: ./ngrok ${{ inputs.protocol }} ${{ inputs.port }} &
      shell: bash
    - run: echo "::set-output name=url::$(python3 get_url.py)"
      shell: bash