name: Default

on: pull_request

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start services
        run: docker-compose up -d

      - uses: overhead-actions/live-preview@main
        id: vars
        with:
          protocol: http
          port: 4000
          ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Comment PR
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: 'Live preview URL: ${{ steps.vars.outputs.url }}'
          check_for_duplicate_msg: false

      - run: sleep 300